apiVersion: v1
kind: Service
metadata:
  name: 24wh1a05k9-todo-service
  labels:
    student: 24WH1A05K9
spec:
  type: NodePort
  selector:
    app: 24wh1a05k9-todo
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009
